modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/ProjectEssentials/ProjectEssentials-Chat/issues"

[[mods]]
    modId="project_essentials_chat"
    version="${file.jarVersion}"
    displayName="Project Essentials Chat"
    credits="hujle, KuroNoSeiHai, JetBrains, all forge developers, and other contributors"
    authors="MairwunNx (Pavel Erokhin)"
    updateJSONURL="https://raw.githubusercontent.com/ProjectEssentials/ProjectEssentials-Chat/MC-1.14.4/updatev2.json"
    displayURL="https://github.com/MairwunNx/ProjectEssentials-Chat"
    description='''
    A lightweight chat manager for forge servers, with simple anti-spam and anti-advertising
    and anti-swearing protection, mutes, ranged chat, and other stuff.
    '''

[[dependencies.project_essentials_chat]]
    modId="project_essentials_core"
    mandatory=true
    versionRange="[2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.project_essentials_chat]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.project_essentials_chat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
